"""add downloaded files table

Revision ID: 04d0ffd13dd3
Revises: 5cde3173142e
Create Date: 2026-07-22 12:09:05.740451

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "04d0ffd13dd3"
down_revision: Union[str, Sequence[str], None] = "5cde3173142e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
