"""add downloaded_files table

Revision ID: 5cde3173142e
Revises:
Create Date: 2026-07-21 11:08:24.158407

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5cde3173142e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "downloaded_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column(
            "downloaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_downloaded_files_downloaded_at"),
        "downloaded_files",
        ["downloaded_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_downloaded_files_filename"),
        "downloaded_files",
        ["filename"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_downloaded_files_filename"), table_name="downloaded_files")
    op.drop_index(
        op.f("ix_downloaded_files_downloaded_at"), table_name="downloaded_files"
    )
    op.drop_table("downloaded_files")
    # ### end Alembic commands ###
